# Sample Cache-Data
version = 0.1
[default.deploy.parameters]
stack_name = "acme-shared-cache-data-storage"
s3_bucket = "cf-templates-somebucket-us-east-2"
s3_prefix = "acme-shared-cache-data-storage"
template_file = "./templates/template-storage-cache-data.yml"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Prefix=\"acme\" ProjectId=\"shared-cache-data\" S3BucketNameOrgPrefix=\"acme\" PermissionsBoundaryArn=\"\" RolePath=\"/\" "
tags = "\"atlantis:Application\"=\"acme-shared-cache-data\" \"atlantis:Prefix\"=\"acme\" CostCenter=\"\" Creator=\"\" Department=\"ACME\" Environment=\"PROD\" Owner=\"\" CodeCommitRepository=\"serverless-deploy-pipeline-atlantis\" DeployedUsing=\"sam\" "
image_repositories = []
