version = 0.1

# ```bash
# sam deploy --profile default --config-file samconfig-acme-sample-storage.toml
# ```

# =====================================================
# Default Deploy Configuration

[default.deploy.parameters]
s3_bucket = "cf-templates-somebucket-us-east-2"
s3_prefix = "acme-sample-static-site-storage"
template_file = "./templates/template-storage-s3-oac-for-cloudfront.yml"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

stack_name = "acme-sample-static-site-storage"
parameter_overrides = "Prefix=\"acme\" ProjectId=\"sample-static-site\" S3BucketNameOrgPrefix=\"acme\" AlarmNotificationEmail=\"\""
tags = "\"atlantis:Application\"=\"acme-sample-static-site\" \"atlantis:Prefix\"=\"acme\" CostCenter=\"\" Creator=\"\" Department=\"ACME\" Environment=\"PROD\" Owner=\"\" CodeCommitRepository=\"serverless-deploy-pipeline-atlantis\" DeployedUsing=\"sam\" "
image_repositories = []

# =====================================================
# Test Deployment Configuration

# There is no Test or Prod Deployment

# =====================================================
# Prod Deployment Configuration

# There is no Test or Prod Deployment